server: 
  port: 8001 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://user:password123@localhost:8761/eureka/    # 指定注册中心的地址 
  instance: 
    preferIpAddress: true 
spring: 
  application: 
    name: microservice-consumer 
microservice-provider:  ##config ribbon 
  ribbon: 
    eureka: 
      enabled: false 
    listOfServers: localhost:8000,localhost:8002,localhost:8003
    ServerListRefreshInterval: 15000